### ISSUE TITLE
No internet access through repeater AP

### ISSUE THREAD

**Issue by uniquetrij** [ArieLevs/Raspberry-WiFi-Repeater#14] opened 2021-11-10 20:41 UTC
I've setup the RPi3B following the manual installation procedure; onboard wlan0 as the AP and another USB Wifi adapter wlan1 for connecting to home router. After the setup, I'm able to connect to the AP from other devices, but there's no internet. There's internet on the pi though, I can browse through the installed chromium. What am I missing?

Linux raspberrypi 5.10.17-v7+ #1414

**Comment by chickentom** [comment] 2021-12-16 17:51
Yeah got the same issue. Raspberry PI got Internet, I See the SSID and can connect to it, get an IP, but no Internet Connection. I can't ping google, or 1.1.1.1 but the name resolution is working.

**Comment by Tarantyev** [comment] 2021-12-20 13:56
I am not sure if it helps you but I had the same problem until I noticed an error in my dhcpcd.conf file. There was a mistake in the "static_routers=" entry. It should point to my main external facing router but I'd made a typo. Once corrected I could get to the Internet from devices associated with the AP.

**Comment by ArieLevs** [comment] 2021-12-25 14:25
I've tested this scenario before, should be covered by
```
# Bridge setup
auto br0
iface br0 inet manual
bridge_ports wlan1 wlan0
```
and allowing iptables,

will try to check it again.

**Comment by ArieLevs** [comment] 2022-02-05 11:25
was not able to reproduce this (routed network)
when switching between `eth0 <-> wlan0` and `wlan1 <-> wlan0` setups, I also have no internet connection until I execute
```
#inter=eth0
inter=wlan1
sudo iptables -t nat -A POSTROUTING -o ${inter} -j MASQUERADE
sudo sh -c "iptables-save > /etc/iptables.ipv4.nat"
```

after setting iptables I get successful internet connection.

closing the issue as was not able to reproduce (using `Linux raspberrypi 5.10.92-v7+ #1514`).

**Closed by ArieLevs** 2022-02-05 11:25 UTC
Labels: bug
